server:
  port: 1112
spring:
  application:
    name: eureka-client
eureka:
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://discovery2:1113/register/eureka/,https://discovery1:1111/register/eureka/
ssl:
  trust-store: codesheepclient.p12
  trust-store-password: codesheep.cn
  key-store: codesheepserver.p12
  key-store-password: codesheep.cn