server:
  port: 1113
  servlet:
    context-path: /register
  ssl:
    enabled: true
    key-store: classpath:codesheepserver.p12
    key-store-password: codesheep.cn
    key-store-type: PKCS12
    key-alias: server
    # 服务端开启客户端校验
    # 1. 生成客户端证书sslClient.p12文件
    # 2. 导出客户端公钥sslClient.cer 文件
    # 3. 将客户端公钥导入服务端证书库 slClient.cer 导入到服务端证书
    client-auth: need
    trust-store: classpath:codesheepclient.p12
    trust-store-type: PKCS12
    trust-store-password: codesheep.cn

eureka:
  instance:
    hostname: discovery2
    securePort: 1113
    securePortEnabled: true
    nonSecurePortEnabled: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: https://discovery1:1111/register/eureka/
ssl:
  key-store: codesheepclient.p12
  key-store-password: codesheep.cn